# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 13:49
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20180113_1334'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='likedislike',
            managers=[
                ('likes_dislikes', django.db.models.manager.Manager()),
            ],
        ),
    ]
