# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-23 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='vote',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='user_profile',
        ),
    ]
