# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20180123_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_dislike',
        ),
    ]
