# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-30 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='label',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
