# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 15:34
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_post'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('comments', django.db.models.manager.Manager()),
            ],
        ),
    ]
